### ISSUE TITLE
Error when a player joined the server with the latest version of Velocity (320)

### ISSUE THREAD

**Issue by NoltoxGit** [Exceptionflug/protocolize#219] opened 2024-01-11 17:03 UTC
**Describe the bug**
Hello,
I have an error when a player joined the server with the latest version of Velocity.

**To Reproduce**
1. Update to the latest version of Velocity _(When I write this, it's 320)_
2. See the error here (https://mclo.gs/mRxV5qb#L80)

**Expected behavior**
No errors.

**Screenshots**
Logs: https://mclo.gs/mRxV5qb#L80

**Proxy environment**
Velocity version: 320
Plugins: `commandforward, luckperms, maintenance, protocolize, pl-hide-pro, viaversion, plan, premiumvanish, spark, ultrastaffchatpro, viabackwards`

**Minecraft versions used**
1.20.4

**Comment by Exceptionflug** [comment] 2024-01-13 09:05
Hello,

sorry. I cannot reproduce this.
![image](https://img.exceptionflug.de/WindowsTerminal_xxVqKsZ5Ny.png)

**Comment by Brickgard** [comment] 2024-01-13 17:15
Stopped by to report the same issue:
Velocity 3.3.0 #320
Minecraft 1.20.4 for client and server
Protocolize 2.3.3:926
Velocity plugins: Luckperms, Protocolize, pl-hide-pro

Seems like Protocolize + Plugin Hide Pro might be a common factor?
Any testing/info I can provide to help track this down?

**Comment by NoltoxGit** [comment] 2024-01-13 17:53
I made a ticket on the [PL-Hide-Pro](https://www.spigotmc.org/resources/✔%EF%B8%8F-plugin-hide-pro-customize-players-tabcompletion-spigot-bungee-velocity-✔%EF%B8%8F.77112/) Discord, and it confirms that the problem comes from the protocolize side.
![image](https://github.com/Exceptionflug/protocolize/assets/75265787/05061cdd-e2ed-4259-9aa0-a0a0e6437a09)

**Comment by Nononitas** [comment] 2024-01-13 18:17
> Hello,
> 
> sorry. I cannot reproduce this. Also running latest Velocity and latest protocolize. ![image](https://camo.githubusercontent.com/209e3db3a6d134a49cc9be062f64b932779c4697767364b4a91d28f13de357dd/68747470733a2f2f696d672e657863657074696f6e666c75672e64652f57696e646f77735465726d696e616c5f787856714b735a354e792e706e67)

Are you sure you are running latest? Are you running it in online mode?

**Comment by Brickgard** [comment] 2024-01-13 18:19
Where are you getting your Protocolize from?
I'm noticing both "can't reproduce" tests are showing Version 2.3.3:939, while ours are showing Version 2.3.3:926
I downloaded [this build](https://github.com/Exceptionflug/protocolize/releases/tag/v2.3.3) - is there a newer/dev build I should be using instead?

**Comment by Nononitas** [comment] 2024-01-13 18:21
Most likely [here](https://ci.exceptionflug.de/job/Protocolize2/) or [here](https://www.exceptionflug.de/protocolize/)

**Comment by Brickgard** [comment] 2024-01-13 18:28
Jenkins brought me up to #939, but the error persists.
The only factor I can find to affect it is whether Pl-Hide-Pro-2.7.5.1 is present or not - removing it immediately removes all errors.

**Comment by Nononitas** [comment] 2024-01-13 18:38
Yes cause plhide is using protocolize's api.

**Comment by Brickgard** [comment] 2024-01-13 18:40
Naturally, just hoping to clearly narrow down how I'm producing the issue is all 😅

**Comment by Exceptionflug** [comment] 2024-01-14 10:29
Try again using this please: https://ci.exceptionflug.de/job/Protocolize2/942/artifact/protocolize-velocity/target/protocolize-velocity.jar

**Comment by NoltoxGit** [comment] 2024-01-14 11:18
> Try again using this please: https://ci.exceptionflug.de/job/Protocolize2/942/artifact/protocolize-velocity/target/protocolize-velocity.jar

Hello,
This seems to be fixed, I no longer get an error when a player joins the server, thank you very much and sorry !

**Comment by Exceptionflug** [comment] 2024-01-14 13:10
Okay, then I will close this now

**Closed by Exceptionflug** 2024-01-14 13:10 UTC
