### ISSUE TITLE
open inventory menu there is a chance of disconnected

### ISSUE THREAD

**Issue by MeowMiaoMiao** [Exceptionflug/protocolize#55] opened 2020-09-09 19:58 UTC
bc: latest
protocolize: latest
When I open inventory menu  there is a chance of disconnected

consolelog
03:54:36 [WARNING] [Ya_Mo_TAT] -> UpstreamBridge - bad packet ID, are mods in use!? Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.BlockPlacement 8 Protocol GAME Direction TO_SERVER
03:54:36 [INFO] [Ya_Mo_TAT] disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.BlockPlacement 8 Protocol GAME Direction TO_SERVER @ io.netty.handler.codec.MessageToMessageDecoder:98

**Comment by MeowMiaoMiao** [comment] 2020-09-10 11:48
19:48:09 [WARNING] [Protocolize] Don't know what item 383:0 is at version 335
19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
19:48:10 [WARNING] [Protocolize] Don't know what item 206:0 is at version 335

**Comment by Exceptionflug** [comment] 2020-09-10 14:16
Hello,



> 
> 
> 19:48:09 [WARNING] [Protocolize] Don't know what item 383:0 is at version 335
> 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> 19:48:10 [WARNING] [Protocolize] Don't know what item 206:0 is at version 335

This is a different problem. This will be handled in another issue: https://github.com/Exceptionflug/protocolize/issues/56



> 
> 
> bc: latest
> protocolize: latest
> When I open inventory menu there is a chance of disconnected
> 
> consolelog
> 03:54:36 [WARNING] [Ya_Mo_TAT] -> UpstreamBridge - bad packet ID, are mods in use!? Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.BlockPlacement 8 Protocol GAME Direction TO_SERVER
> 03:54:36 [INFO] [Ya_Mo_TAT] disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.BlockPlacement 8 Protocol GAME Direction TO_SERVER @ io.netty.handler.codec.MessageToMessageDecoder:98

Please tell me which exact client and spigot server you are using to reproduce this.

**Comment by MeowMiaoMiao** [comment] 2020-09-11 04:58
> Hello,
> 
> > 19:48:09 [WARNING] [Protocolize] Don't know what item 383:0 is at version 335
> > 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> > 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> > 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> > 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> > 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> > 19:48:10 [WARNING] [Protocolize] Don't know what item 383:0 is at version 340
> > 19:48:10 [WARNING] [Protocolize] Don't know what item 206:0 is at version 335
> 
> This is a different problem. This will be handled in another issue: #56
> 
> > bc: latest
> > protocolize: latest
> > When I open inventory menu there is a chance of disconnected
> > consolelog
> > 03:54:36 [WARNING] [Ya_Mo_TAT] -> UpstreamBridge - bad packet ID, are mods in use!? Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.BlockPlacement 8 Protocol GAME Direction TO_SERVER
> > 03:54:36 [INFO] [Ya_Mo_TAT] disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.BlockPlacement 8 Protocol GAME Direction TO_SERVER @ io.netty.handler.codec.MessageToMessageDecoder:98
> 
> Please tell me which exact client and spigot server you are using to reproduce this.

spigot: 1.8.8
bungeecord: 1.16.2-latest
client: 1.8.9
It seems that all versions of the client will have this problem
When the problem is reproduced, it will reproduce multiple times in succession

**Comment by Exceptionflug** [comment] 2020-09-14 06:22
Hey the issue should be resolved after the latest update

**Comment by Exceptionflug** [comment] 2020-09-18 14:28
I will close this since there is no reaction anymore.

**Closed by Exceptionflug** 2020-09-18 14:28 UTC
