### ISSUE TITLE
IllegalReferenceCountException error

### ISSUE THREAD

**Issue by CodfishBender** [Exceptionflug/protocolize#133] opened 2022-06-13 10:23 UTC
**Describe the bug**
Making a trade on a 1.19 bungeecord/server will produce the error: ``disconnected with: DecoderException : io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1 @ io.netty.handler.codec.MessageToMessageDecoder:98``
This was reproduced locally with only protocolize. Removing protocolize resolves the issue.

**To Reproduce**
1. Create a 1.19 BungeeCord server with Protocolize.
2. Create a plain 1.19 Paper server. 
3. Summon a villager and assign any job to them.
4. Select the item in the trade GUI and see the error.

**Expected behavior**
The player should not be kicked from the game.

**Proxy environment**
Proxy: BungeeCord Build 1644
Server: Paper 1.19-8

**Minecraft versions used**
Minecraft latest 1.19

**Comment by Exceptionflug** [comment] 2022-06-13 12:21
Hello, please send the full log for investigation.

**Comment by Exceptionflug** [comment] 2022-06-13 12:23
Duplicate of https://github.com/Exceptionflug/protocolize/issues/131

And this issue has already been fixed. Please download the latest build of Protocolize.

**Closed by Exceptionflug** 2022-06-13 12:23 UTC
