### ISSUE TITLE
Pipeline is not initialized

### ISSUE THREAD

**Issue by Teyir** [Exceptionflug/protocolize#118] opened 2022-03-16 14:32 UTC
**Describe the bug**
I have this message on my console when a player disconnect (not all time)
`[dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
[dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer`

**To Reproduce**
1. Launch the server
2. Player connect / disconnect

**Screenshots**
![image](https://user-images.githubusercontent.com/60007549/158613644-e0fe8840-82b8-4143-a8e5-687adc434b0e.png)

**Proxy environment**
Velocity 3.1.2-SNAPSHOT (git-94e8b0df-b121)
Plugins: luckperms, motd, protocolize, pl-hide-pro, plan, playerlist, slashserver, spark, tcpshield, vtools

**Minecraft versions used**
Minecraft 1.18.1 (pufferfish and purpur)

**Comment by Exceptionflug** [comment] 2022-03-16 20:31
Duplicate of https://github.com/Exceptionflug/protocolize/issues/115

**Closed by Exceptionflug** 2022-03-16 20:31 UTC
