### ISSUE TITLE
FastDecoderException w/ BlockPlacement class

### ISSUE THREAD

**Issue by RealGatt** [Exceptionflug/protocolize#34] opened 2020-03-30 07:48 UTC
Hi there,

I've recently been getting the following error with Protocolize 1.5.4-SNAPSHOT:105

```
[07:33:21 WARN]: [REDACTED|Gatt] -> UpstreamBridge - bad packet ID, are mods in use!? Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.BlockPlacement 8 Protocol GAME Direction TO_SERVER
[07:33:21 INFO]: [Gatt] disconnected with: FastDecoderException : Error decoding packet class BlockPlacement with contents:
+-------------------------------------------------+
| 0 1 2 3 4 5 6 7 8 9 a b c d e f |
+--------+-------------------------------------------------+----------------+
|00000000| 08 ff ff ff ff ff ff ff ff ff 00 00 00 00 00 00 |................|
|00000010| 00 00 00 |... |
+--------+-------------------------------------------------+----------------+
```

It occurs when I switch between servers, and causes the client to disconnect.

Following is a list of plugins on my Proxy server:
> BadlionClientModAPIBungee
> BungeeMOTD
> BungeePluginManager
> LuckPerms
> MCCommons
> Protocolize
> spark
> ViaVersion 3.0.0

If you need any other details, let me know.

**Comment by Exceptionflug** [comment] 2020-03-31 14:49
Hey,

on which minecraft versions does this occur?

**Comment by RealGatt** [comment] 2020-04-01 06:17
It occurs when going from a 1.8.9 Server to a 1.14.4 server, on a 1.15.2 Client. It hasn't happened since I reported it, so I've been unable to reproduce it w/ other version mixtures.

**Comment by Exceptionflug** [comment] 2020-04-01 10:43
I will try to reproduce this when I'm home.

**Comment by Exceptionflug** [comment] 2020-04-01 18:50
I cannot reproduce this using Waterfall build 326 and protocolize 1.5.4-SNAPSHOT build 105. I have set up a 1.8.9 spigot server and a 1.14.4 spigot server. When I switch the servers using Minecraft 1.15.2 everything is fine.

**Comment by RealGatt** [comment] 2020-04-02 03:13
I've updated Waterfall and the issue doesn't seem to occur anymore. If it occurs again I'll reopen the ticket :)

**Comment by RealGatt** [comment] 2020-04-08 07:59
Reopening this issue as I've figured out the cause and how to properly replicate it.

1.8 Server w/ ViaVersion (3.0.0-ABSTRACTION) installed
Waterfall server w/ ViaVersion (3.0.0-ABSTRACTION) installed

Login w/ a client above 1.8. I managed to replicate w/ 1.14.4 and 1.15.2.

Rightclick a block - hand contents doesn't matter.

```
[07:53:29 WARN]: [/<redacted>|Gatt] -> UpstreamBridge - bad packet ID, are mods in use!? Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.BlockPlacement 8 Protocol GAME Direction TO_SERVER
[07:53:29 INFO]: [Gatt] disconnected with: FastDecoderException : Error decoding packet class BlockPlacement with contents:
+-------------------------------------------------+
| 0 1 2 3 4 5 6 7 8 9 a b c d e f |
+--------+-------------------------------------------------+----------------+
|00000000| 08 00 00 00 00 fc 00 00 01 01 00 00 00 00 00 00 |................|
|00000010| 04 10 0a |... |
+--------+-------------------------------------------------+----------------+
```

**https://www.youtube.com/watch?v=tA1yZBJW71c&feature=youtu.be**

Video showing the bug.

Also getting an issue where Protocolize Inventories don't show up to 1.15.2 clients on a 1.15.2 server, but I'll open another ticket for that as it's not critical.

**Comment by Exceptionflug** [comment] 2020-04-12 09:30
Hey,

I am sorry that I reply so lately. I will take a look at that when I have more time.

**Comment by RealGatt** [comment] 2020-04-12 10:26
No worries at all :)

It's not a major issue currently. We've just removed ViaVersion from the Proxy ^_^

**Comment by Exceptionflug** [comment] 2020-04-18 09:48
Hey,

I still cannot reproduce this using the latest ViaVersion Abstraction version from CI. Can you provide me your used version?

**Comment by RealGatt** [comment] 2020-04-18 10:06
It would've been build # 61 found here: https://ci.viaversion.com/job/ViaVersion-Abstraction/61/

It may have been fixed since me reporting it.

**Comment by Exceptionflug** [comment] 2020-04-28 05:28
Since the bug isn't occurring anymore. I will close this issue.

**Closed by Exceptionflug** 2020-04-28 05:28 UTC
