### ISSUE TITLE
Remove item from player inventory

### ISSUE THREAD

**Issue by MrArtem1337** [Exceptionflug/protocolize#37] opened 2020-05-31 10:32 UTC
Hi, im created inventory. But after clicking on an item in the player’s inventory, it disappears or gives a null response.
Exist item in player inventory:
![image](https://user-images.githubusercontent.com/39164307/83350166-e8600f80-a342-11ea-8dbb-3abe4a40eff0.png)
Not exist: 
![image](https://user-images.githubusercontent.com/39164307/83350179-0594de00-a343-11ea-999a-fb94944ed37a.png)

**Comment by Exceptionflug** [comment] 2020-05-31 10:36
Duplicate of https://github.com/Exceptionflug/protocolize/issues/35

**Closed** 2020-05-31 10:36 UTC
