### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Iimpro608** [Exceptionflug/protocolize#122] opened 2022-04-06 00:11 UTC
[03:02:17 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
[03:02:17 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer

**Proxy environment**
velocity 3.1.1
(https://i.gyazo.com/bec3432b8ac13ccaf7593718a555b90f.png)

any suggestion how to remove this from console?

**Comment by Exceptionflug** [comment] 2022-04-20 08:13
Duplicate of https://github.com/Exceptionflug/protocolize/issues/115

**Closed by Exceptionflug** 2022-04-20 08:13 UTC
