### ISSUE TITLE
Close Game

### ISSUE THREAD

**Issue by RubenArtz** [Exceptionflug/protocolize#72] opened 2021-01-31 05:34 UTC
Hello I have detected a new error I do not know if it is my error or the plugin but when I close minecraft without pressing the close button the game gives errors.
https://pastebin.com/24L12PqD

[https://youtu.be/HgBHSk5Nz6Y](url)

**Comment by RubenArtz** [comment] 2021-01-31 05:35
https://youtu.be/HgBHSk5Nz6Y

**Comment by Exceptionflug** [comment] 2021-01-31 09:35
Hello, this is a duplicate of https://github.com/Exceptionflug/protocolize/issues/68

**Closed by Exceptionflug** 2021-01-31 09:35 UTC
